
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzfvvhdyohlgdkvbpvmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6ZnZ2aGR5b2hsZ2RrdmJwdm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTMzNTUsImV4cCI6MjA2MjQ4OTM1NX0.nq_YzBQF1U9qOLDCCPC-XYakToVfMVCkwxiqSJ9vZ88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
